[project]
name = "exercicios-de-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joao-Inacio", email = "joaoinacio206@protonmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
exercicios-de-python = "exercicios_de_python:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
